apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/name: Foo
      app.kubernetes.io/signed: 'true'
      app.kubernetes.io/description: accept
    name: signedimage
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
      spec:
        containers:
          - name: foo
            image: ghcr.io/garethahealy/kyverno-signed:latest
