apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-admin
rules:
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - "*"
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - get
    - list