name: Generate README.html

on: [push, pull_request]

jobs:
  doc_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1

      - name: Content checker
        uses: errata-ai/vale-action@v1.4.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true

      - uses: docker://pandoc/core:2.9
        with:
          args: -o README.html README.md

